# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160623_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name=b'Is Paid Member'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name=b'Facebook profile url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
