# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160624_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goalDate',
            field=models.DateField(default=datetime.date(2016, 6, 25)),
        ),
    ]
