# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20160624_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='startDate',
            field=models.DateField(default=datetime.date(2016, 6, 24)),
        ),
    ]
