# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20160624_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goalWeight',
            field=models.IntegerField(blank=True, default=160, help_text=b'in lbs'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.TextField(blank=True, default=b'Running, Basketball, Tennis'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='startWeight',
            field=models.IntegerField(blank=True, default=180, help_text=b'in lbs'),
        ),
    ]
