# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20160624_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default=b'Alex Smith', max_length=120),
        ),
    ]
