# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20160624_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('name', models.CharField(default=b'Anonymous', max_length=120)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default=b'Alex Smith', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goalDate',
            field=models.DateField(default=datetime.date(2016, 7, 8)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='startDate',
            field=models.DateField(default=datetime.date(2016, 6, 26)),
        ),
    ]
