# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20160627_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.TextField(blank=True, default=datetime.datetime(2016, 6, 27, 14, 29, 22, 23701, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
