# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20160627_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, default=b'John Smith', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default=b'John Smith', max_length=120),
        ),
    ]
